# Generated by Django 6.0.5 on 2026-05-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedrecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
