# Generated by Django 6.0.5 on 2026-05-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg_app', '0002_normalizedrecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedrecord',
            name='normalization_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
